<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UseXunit>true</UseXunit>
    <UseExtensionsDependencyInjection>true</UseExtensionsDependencyInjection>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net48'">
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  
</Project>
