<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UseExtensionsDependencyInjection>true</UseExtensionsDependencyInjection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="4.4.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.2.0" />
  </ItemGroup>
  
</Project>
