<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Condition="'$(TargetFramework)' == 'net48'">
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\InjectedTests.Extensions.DependencyInjection\InjectedTests.Extensions.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\src\InjectedTests.Extensions.Hosting\InjectedTests.Extensions.Hosting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Update="Microsoft.Extensions.DependencyInjection" Version="9.0.11" />
    <PackageReference Update="Microsoft.Extensions.Hosting" Version="9.0.11" />
  </ItemGroup>

</Project>
